name: ten_min_rescue
description: Suraksha Kavach - Emergency Ambulance Dispatch App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter

  # Firebase (Spark free plan — no billing required)
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  image_picker: ^1.1.2

  # State management
  flutter_riverpod: ^2.5.1

  # Navigation
  go_router: ^14.2.7

  # Maps & Location (OpenStreetMap — free, no API key)
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  geolocator: ^13.0.1
  permission_handler: ^11.3.1

  # Utilities
  shared_preferences: ^2.3.2
  intl: ^0.19.0
  uuid: ^4.4.2
  http: ^1.2.2
  url_launcher: ^6.3.0
  google_fonts: ^6.2.1
  wakelock_plus: ^1.2.8
  firebase_messaging: ^15.1.3
  flutter_local_notifications: ^19.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
